# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wzorwynikow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wzor_wynikow(object):
    def setupUi(self, Wzor_wynikow):
        Wzor_wynikow.setObjectName("Wzor_wynikow")
        Wzor_wynikow.resize(906, 395)
        self.Tabela_wynikow = QtWidgets.QTableWidget(Wzor_wynikow)
        self.Tabela_wynikow.setGeometry(QtCore.QRect(30, 40, 841, 261))
        self.Tabela_wynikow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Tabela_wynikow.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Tabela_wynikow.setObjectName("Tabela_wynikow")
        self.Tabela_wynikow.setColumnCount(6)
        self.Tabela_wynikow.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela_wynikow.setItem(0, 0, item)
        self.label = QtWidgets.QLabel(Wzor_wynikow)
        self.label.setGeometry(QtCore.QRect(370, 315, 301, 41))
        self.label.setObjectName("label")

        self.retranslateUi(Wzor_wynikow)
        QtCore.QMetaObject.connectSlotsByName(Wzor_wynikow)

    def retranslateUi(self, Wzor_wynikow):
        _translate = QtCore.QCoreApplication.translate
        Wzor_wynikow.setWindowTitle(_translate("Wzor_wynikow", "Form"))
        item = self.Tabela_wynikow.verticalHeaderItem(0)
        item.setText(_translate("Wzor_wynikow", "New Row"))
        item = self.Tabela_wynikow.verticalHeaderItem(1)
        item.setText(_translate("Wzor_wynikow", "New Row"))
        item = self.Tabela_wynikow.verticalHeaderItem(2)
        item.setText(_translate("Wzor_wynikow", "New Row"))
        item = self.Tabela_wynikow.verticalHeaderItem(3)
        item.setText(_translate("Wzor_wynikow", "New Row"))
        item = self.Tabela_wynikow.verticalHeaderItem(4)
        item.setText(_translate("Wzor_wynikow", "New Row"))
        item = self.Tabela_wynikow.verticalHeaderItem(5)
        item.setText(_translate("Wzor_wynikow", "New Row"))
        item = self.Tabela_wynikow.horizontalHeaderItem(0)
        item.setText(_translate("Wzor_wynikow", "V_NH3 (dm^3/h)"))
        item = self.Tabela_wynikow.horizontalHeaderItem(1)
        item.setText(_translate("Wzor_wynikow", "Tem (oC)"))
        item = self.Tabela_wynikow.horizontalHeaderItem(2)
        item.setText(_translate("Wzor_wynikow", "P (atm)"))
        item = self.Tabela_wynikow.horizontalHeaderItem(3)
        item.setText(_translate("Wzor_wynikow", "m. kat(g)"))
        item = self.Tabela_wynikow.horizontalHeaderItem(4)
        item.setText(_translate("Wzor_wynikow", "k"))
        item = self.Tabela_wynikow.horizontalHeaderItem(5)
        item.setText(_translate("Wzor_wynikow", "k/ko"))
        __sortingEnabled = self.Tabela_wynikow.isSortingEnabled()
        self.Tabela_wynikow.setSortingEnabled(False)
        self.Tabela_wynikow.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Wzor_wynikow", "Teks"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wzor_wynikow = QtWidgets.QWidget()
    ui = Ui_Wzor_wynikow()
    ui.setupUi(Wzor_wynikow)
    Wzor_wynikow.show()
    sys.exit(app.exec_())
